CREATE TABLE IF NOT EXISTS short_dramas (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_id INT UNSIGNED NOT NULL,
    source_name VARCHAR(128) NOT NULL DEFAULT '',
    external_id VARCHAR(255) NOT NULL,
    name VARCHAR(500) NOT NULL,
    subtitle VARCHAR(500) NOT NULL DEFAULT '',
    remarks VARCHAR(255) NOT NULL DEFAULT '',
    poster_url VARCHAR(1500) NOT NULL DEFAULT '',
    year VARCHAR(16) NOT NULL DEFAULT '',
    area VARCHAR(128) NOT NULL DEFAULT '',
    language VARCHAR(128) NOT NULL DEFAULT '',
    actors TEXT NOT NULL,
    director VARCHAR(255) NOT NULL DEFAULT '',
    score VARCHAR(32) NOT NULL DEFAULT '',
    type_name VARCHAR(128) NOT NULL DEFAULT '',
    class_name VARCHAR(128) NOT NULL DEFAULT '',
    duration VARCHAR(64) NOT NULL DEFAULT '',
    blurb TEXT NOT NULL,
    content TEXT NOT NULL,
    total_episodes INT UNSIGNED NOT NULL DEFAULT 0,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    episodes_json JSON NOT NULL,
    scraped_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_short_dramas_source_external (source_id, external_id),
    KEY idx_short_dramas_scraped_at (scraped_at),
    KEY idx_short_dramas_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
